#!/bin/bash

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/puppet/bin

if [ -z "$1" ]; then
    echo "Usage: $0 [hostname]"
    exit 1
fi

if [ `id -u` -gt 0 ]; then
    echo "Error: Must be root"
    exit 1
fi

hn=$1
shift

if [ ! -r manifests/$hn.pp ]; then
    echo "Cannot find manifests/$hn.pp"
    exit 1
fi

puppet apply --modulepath=modules manifests/$hn.pp $@
